spring:
  application:
    name: dotory

  jwt:
    secret: ${JWT_SECRET_KEY}
    tokens:
      expire:
        access_token: ${ACCESS_TOKEN_EXPIRE_TIME}
        refresh_token: ${REFRESH_TOKEN_EXPIRE_TIME}

  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      cloudfront:
        domain: ${AWS_CLOUDFRONT_DOMAIN}
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  mail:
    host: smtp.worksmobile.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: true

        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: false
            trust: smtp.worksmobile.com
          transport:
            protocol: smtp
            mime:
              charset: UTF-8
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  forward-headers-strategy: native
